version: "3"
services:
  app:
    image: quarkus-demo-native
    links:
      - postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo_quarkus
    ports:
      - 5432:5433